site_name: 'test-1'
site_description: 'Main documentation for test-1'
repo_url: https://github.com/qburst-praven/test-1
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting Started: 'docs/index.md'
